---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kavir
  namespace: "{{ .Release.Namespace }}"
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kavir
          imagePullSecrets:
          - name: kavir-container-registry
          containers:
          - name: kavir
            image: "{{ .Values.containerRegistry.image }}"
            env:
            - name: clusterName
              value: "{{ .Values.clusterName }}"
            - name: gitRepoUrl
              value: "{{ .Values.git.repoUrl }}"
            - name: gitProjectAccessToken
              valueFrom:
                secretKeyRef:
                  name: kavir-git-project-access-token
                  key: token
            - name: gitUserName
              value: "{{ .Values.git.userName }}"
            - name: gitUserEmail
              value: "{{ .Values.git.userEmail }}"
            - name: reportNamespaces
              value: "{{ .Values.report.namespaces }}"
            - name: reportDeployments
              value: "{{ .Values.report.scope.deployments }}"
            - name: reportReplicasets
              value: "{{ .Values.report.scope.replicasets }}"
            - name: reportStatefulsets
              value: "{{ .Values.report.scope.statefulsets }}"
            - name: reportDaemonsets
              value: "{{ .Values.report.scope.daemonsets }}"
            - name: reportJobs
              value: "{{ .Values.report.scope.jobs }}"
            - name: reportCronjobs
              value: "{{ .Values.report.scope.cronjobs }}"
            - name: reportReplicationcontrollers
              value: "{{ .Values.report.scope.replicationcontrollers }}"
            securityContext:
              runAsNonRoot: true
              allowPrivilegeEscalation: false
          restartPolicy: OnFailure
...
