---
apiVersion: v1
kind: Secret
metadata:
  name: kavir-container-registry
  namespace: "{{ .Release.Namespace }}"
data:
  .dockerconfigjson: {{ .Values.containerRegistry.dockerconfigjson | b64enc }}
type: kubernetes.io/dockerconfigjson
...