---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kavir
  namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kavir
subjects:
- kind: ServiceAccount
  name: kavir
  namespace: "{{ .Release.Namespace }}"
...