---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kavir
  namespace: "{{ .Release.Namespace }}"
rules:
- apiGroups:
  - ""
  resources:
    - 'replicationcontrollers'
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - "apps"
  resources:
    - 'deployments'
    - 'replicasets'
    - 'statefulsets'
    - 'daemonsets'
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - "batch"
  resources:
    - 'jobs'
    - 'cronjobs'
  verbs:
    - get
    - list
    - watch
...
